In [1]:
import pandas as pd

In [4]:
oil = pd.read_csv("../retailFiles/oil.csv")
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [5]:
columns = ["Date", "Oil Price"]
oil_1 = pd.read_csv("../retailFiles/oil.csv",
                    header=0,
                    names=columns)
oil_1.head()

         Date  Oil Price
0  2013-01-01        NaN
1  2013-01-02      93.14
2  2013-01-03      92.97
3  2013-01-04      93.12
4  2013-01-07      93.20