In [1]:
import pandas as pd

can select rows to read in from the top with the "nrows" argument, and specify any rows to skip with "skiprows"

Can specify strings (or other values) to treat as missing values with the "na_values" argument \
They are replaced with NumPy NaN values

In [3]:
columns = ["Date", "Oil Price"]
oil = pd.read_csv("../retailFiles/oil.csv",
                  header=0,
                  names=columns,
                  index_col="Date",
                  parse_dates=True,
                  usecols=["Date", "Oil Price"],
                  skiprows=[0], # Skip the first row
                  nrows=3, # Use the first 3 rows
#                 skiprows = lambda x: x % 2 == 1   Skip every odd rows
                  )
oil.head()

            Oil Price
Date
2013-01-02      93.14
2013-01-03      92.97
2013-01-04      93.12

In [5]:
columns = ["Date", "Oil Price"]
oil_1 = pd.read_csv("../retailFiles/oil.csv",
                  header=0,
                  names=columns,
                  index_col="Date",
                  parse_dates=True,
                  usecols=["Date", "Oil Price"],
                  na_values= 93.14 # Change rows with value = 93.14 into NaN value
                  )
oil_1.head()

            Oil Price
Date
2013-01-01        NaN
2013-01-02        NaN
2013-01-03      92.97
2013-01-04      93.12
2013-01-07      93.20