In [1]:
import pandas as pd

In [ ]:
# read first sheet
pd.read_excel("../retailFiles/premier_league_games.xlsx")

       id             league_name     season  HomeGoals  AwayGoals
0    1729  England Premier League  2008/2009          1          1
1    1730  England Premier League  2008/2009          1          0
2    1731  England Premier League  2008/2009          0          1
3    1732  England Premier League  2008/2009          2          1
4    1733  England Premier League  2008/2009          4          2
..    ...                     ...        ...        ...        ...
375  2104  England Premier League  2008/2009          1          1
376  2105  England Premier League  2008/2009          0          3
377  2106  England Premier League  2008/2009          1          1
378  2107  England Premier League  2008/2009          0          4
379  2108  England Premier League  2008/2009          0          1

[380 rows x 5 columns]

In [ ]:
# read second sheet
pd.read_excel("../retailFiles/premier_league_games.xlsx", sheet_name=1)

       id             league_name     season  HomeGoals  AwayGoals
0    2109  England Premier League  2009/2010          1          0
1    2110  England Premier League  2009/2010          2          1
2    2111  England Premier League  2009/2010          0          2
3    2112  England Premier League  2009/2010          1          6
4    2113  England Premier League  2009/2010          0          2
..    ...                     ...        ...        ...        ...
375  2484  England Premier League  2009/2010          2          1
376  2485  England Premier League  2009/2010          1          0
377  2486  England Premier League  2009/2010          1          1
378  2487  England Premier League  2009/2010          1          2
379  2488  England Premier League  2009/2010          3          1

[380 rows x 5 columns]

In [ ]:
# concat both sheets together
pd.concat(
    pd.read_excel("../retailFiles/premier_league_games.xlsx", sheet_name=None),
    ignore_index=True
)

       id             league_name     season  HomeGoals  AwayGoals
0    1729  England Premier League  2008/2009          1          1
1    1730  England Premier League  2008/2009          1          0
2    1731  England Premier League  2008/2009          0          1
3    1732  England Premier League  2008/2009          2          1
4    1733  England Premier League  2008/2009          4          2
..    ...                     ...        ...        ...        ...
755  2484  England Premier League  2009/2010          2          1
756  2485  England Premier League  2009/2010          1          0
757  2486  England Premier League  2009/2010          1          1
758  2487  England Premier League  2009/2010          1          2
759  2488  England Premier League  2009/2010          3          1

[760 rows x 5 columns]