# Pivot Table Practice Exercises — English Premier League

You're a football analyst digging into eight seasons of Premier League results with `pivot_table()`. Work through the exercises **in order** — later ones build on the tables you make earlier.

Each question describes the *outcome* you need, not the exact method — figure out which arguments fit. If you get stuck, the `*(covers: ...)*` line points you back to your `8.PivotTables` lesson notebook.

Run the setup cell below first — it loads `premier_league_games_full.xlsx`. Then write your answers in the empty cell under each exercise. When you're done, come back and I'll check them.

In [1]:
import numpy as np
import pandas as pd

premier_league = pd.read_excel("../retailFiles/premier_league_games_full.xlsx")
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

## Exercise 1 — Your First Pivot Table
*(covers: PivotTables — index / columns / values / aggfunc)*

1. Build a pivot table with **one row per home team**, **one column per season**, and each cell holding the **total home goals** that team scored at home in that season.
2. Now build the same table, but only for three teams: `"Liverpool"`, `"Manchester United"`, and `"Tottenham Hotspur"`. Save it as `three_teams`.

In [3]:
# 1. Total home goals by home team (rows) and season (columns)
premier_league.pivot_table(index="HomeTeam",
                           columns="season",
                           values="HomeGoals",
                           aggfunc="sum"
                           )

# 2. Same table, limited to three teams -> three_teams
premier_league.query("HomeTeam in ['Liverpool', 'Manchester United', 'Tottenham Hotspur']").pivot_table(index="HomeTeam",
                                                                                                        columns="season",
                                                                                                        values="HomeGoals",
                                                                                                        aggfunc="sum")

season,2008/2009,2009/2010,2010/2011,2011/2012,2012/2013,2013/2014,2014/2015,2015/2016
HomeTeam,,,,,,,,
Liverpool,41,43,37,24,33,53,30,33
Manchester United,43,52,49,52,45,29,41,27
Tottenham Hotspur,21,40,30,39,29,30,31,35

## Exercise 2 — Row & Column Totals
*(covers: PivotTables — margins)*

Rebuild the three-team pivot from Exercise 1, but this time add a **row of totals and a column of totals**, so you can read each team's grand total home goals and each season's total across those teams.

In [4]:
# Three-team pivot with row and column totals
premier_league.query("HomeTeam in ['Liverpool', 'Manchester United', 'Tottenham Hotspur']").pivot_table(index="HomeTeam",
                                                                                                        columns="season",
                                                                                                        values="HomeGoals",
                                                                                                        aggfunc="sum",
                                                                                                        margins=True
                                                                                                        )

season,2008/2009,2009/2010,2010/2011,2011/2012,2012/2013,2013/2014,2014/2015,2015/2016,All
HomeTeam,,,,,,,,,
Liverpool,41,43,37,24,33,53,30,33,294
Manchester United,43,52,49,52,45,29,41,27,338
Tottenham Hotspur,21,40,30,39,29,30,31,35,255
All,105,135,116,115,107,112,102,95,887

## Exercise 3 — Two Aggregations at Once
*(covers: PivotTables — list of aggfuncs)*

For the same three teams, build a pivot table (rows = home team, columns = season) where each cell shows **both the sum and the mean** of home goals — in a single table, not two separate ones.

In [5]:
# Sum AND mean of home goals per team per season
premier_league.query("HomeTeam in ['Liverpool', 'Manchester United', 'Tottenham Hotspur']").pivot_table(index="HomeTeam",
                                                                                                        columns="season",
                                                                                                        values="HomeGoals",
                                                                                                        aggfunc=["sum", "mean"])

                        sum                                                    \
season            2008/2009 2009/2010 2010/2011 2011/2012 2012/2013 2013/2014
HomeTeam
Liverpool                41        43        37        24        33        53
Manchester United        43        52        49        52        45        29
Tottenham Hotspur        21        40        30        39        29        30

                                           mean                                \
season            2014/2015 2015/2016 2008/2009 2009/2010 2010/2011 2011/2012
HomeTeam
Liverpool                30        33  2.157895  2.263158  1.947368  1.263158
Manchester United        41        27  2.263158  2.736842  2.578947  2.736842
Tottenham Hotspur        31        35  1.105263  2.105263  1.578947  2.052632


season            2012/2013 2013/2014 2014/2015 2015/2016
HomeTeam
Liverpool          1.736842  2.789474  1.578947  1.736842
Manchester United  2.368421  1.526316  2.157895  1.421053
Tottenham Hotspur  1.526316  1.578947  1.631579  1.842105

## Exercise 4 — Aggregating Multiple Value Columns
*(covers: PivotTables — dict aggfunc)*

1. For the three teams, build a pivot table (rows = home team, columns = season) that shows the **sum of `HomeGoals`** *and* the **sum of `AwayGoals`** side by side.
2. Do it again, but this time take the **sum of `HomeGoals`** and the **mean of `AwayGoals`** — each value column with its own aggregation.

In [10]:
# 1. Sum of HomeGoals and sum of AwayGoals
premier_league.query("HomeTeam in ['Liverpool', 'Manchester United', 'Tottenham Hotspur']").pivot_table(index="HomeTeam",
                                                                                                        columns="season",
                                                                                                        aggfunc={"HomeGoals":"sum", "AwayGoals":"sum"})

# 2. Sum of HomeGoals and mean of AwayGoals
premier_league.query("HomeTeam in ['Liverpool', 'Manchester United', 'Tottenham Hotspur']").pivot_table(index="HomeTeam",
                                                                                                        columns="season",
                                                                                                        aggfunc={"HomeGoals":"sum", "AwayGoals":"mean"})

                  AwayGoals                                                    \
season            2008/2009 2009/2010 2010/2011 2011/2012 2012/2013 2013/2014
HomeTeam
Liverpool          0.684211  0.789474  0.736842  0.842105  0.842105  0.947368
Manchester United  0.684211  0.631579  0.631579  1.000000  1.000000  1.105263
Tottenham Hotspur  0.526316  0.631579  1.000000  0.894737  0.947368  1.210526

                                      HomeGoals                                \
season            2014/2015 2015/2016 2008/2009 2009/2010 2010/2011 2011/2012
HomeTeam
Liverpool          1.052632  1.157895        41        43        37        24
Manchester United  0.789474  0.473684        43        52        49        52
Tottenham Hotspur  1.263158  0.789474        21        40        30        39


season            2012/2013 2013/2014 2014/2015 2015/2016
HomeTeam
Liverpool                33        53        30        33
Manchester United        45        29        41        27
Tottenham Hotspur        29        30        31        35

## Exercise 5 — Turn a Pivot Table into a Heatmap
*(covers: PivotTables — .style.background_gradient)*

1. Build a pivot table of **total home goals** for the three teams (rows = home team, columns = season) and save it as `goals_pivot`.
2. Style `goals_pivot` as a **heatmap** using a red-yellow-green colour map, with the gradient applied **across each row** so you can see each team's best and worst seasons.

In [11]:
# 1. goals_pivot: total home goals, three teams
goals_pivot=premier_league.query("HomeTeam in ['Liverpool', 'Manchester United', 'Tottenham Hotspur']").pivot_table(index="HomeTeam",
                                                                                                        columns="season",
                                                                                                        values="HomeGoals",
                                                                                                        aggfunc="sum")

# 2. Heatmap: red-yellow-green gradient across each row
goals_pivot.style.background_gradient(cmap="RdYlGn", axis=1)