In [1]:
import numpy as np
import pandas as pd

In [9]:
oil = pd.read_csv("../retailFiles/oil.csv")
oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [10]:
oil.shape

(1218, 2)

In [11]:
oil.index

RangeIndex(start=0, stop=1218, step=1)

In [12]:
oil.columns

Index(['date', 'dcoilwtico'], dtype='object')

In [13]:
oil.columns = ["price_date", "oil_price"]

In [14]:
oil

      price_date  oil_price
0     2013-01-01        NaN
1     2013-01-02      93.14
2     2013-01-03      92.97
3     2013-01-04      93.12
4     2013-01-07      93.20
...          ...        ...
1213  2017-08-25      47.65
1214  2017-08-28      46.40
1215  2017-08-29      46.46
1216  2017-08-30      45.96
1217  2017-08-31      47.26

[1218 rows x 2 columns]

In [15]:
oil.axes

[RangeIndex(start=0, stop=1218, step=1),
 Index(['price_date', 'oil_price'], dtype='object')]

In [16]:
oil.dtypes

price_date     object
oil_price     float64
dtype: object