In [26]:
import numpy as np
import pandas as pd

In [27]:
retail = pd.read_csv("../retailFiles/retail.csv")

.query() method lets you use SQL-like syntax to filter DataFrames
- you can specify any number of filtering conditions by using the "and" & "or" keywords
- you can reference variables by using the "@" symbol

In [28]:
retail.query("family in ['CLEANING', 'DAIRY'] and sales > 0")

              id        date  store_nbr    family   sales  onpromotion
568      1946512  2016-01-01         25  CLEANING   734.0            0
569      1946513  2016-01-01         25     DAIRY  1033.0           11
1789     1947733  2016-01-02          1  CLEANING   526.0            3
1790     1947734  2016-01-02          1     DAIRY   627.0           15
1822     1947766  2016-01-02         10  CLEANING  1216.0            4
...          ...         ...        ...       ...     ...          ...
1054853  3000797  2017-08-15          7     DAIRY  1279.0           25
1054885  3000829  2017-08-15          8  CLEANING  1198.0           13
1054886  3000830  2017-08-15          8     DAIRY  1330.0           24
1054918  3000862  2017-08-15          9  CLEANING  1439.0           25
1054919  3000863  2017-08-15          9     DAIRY   835.0           19

[62415 rows x 6 columns]

In [29]:
avg_sales = retail.loc[:, "sales"].mean()
avg_sales

np.float64(457.72248700136424)

In [30]:
retail.query("family in ['CLEANING', 'DAIRY'] and sales > @avg_sales")

              id        date  store_nbr    family   sales  onpromotion
568      1946512  2016-01-01         25  CLEANING   734.0            0
569      1946513  2016-01-01         25     DAIRY  1033.0           11
1789     1947733  2016-01-02          1  CLEANING   526.0            3
1790     1947734  2016-01-02          1     DAIRY   627.0           15
1822     1947766  2016-01-02         10  CLEANING  1216.0            4
...          ...         ...        ...       ...     ...          ...
1054853  3000797  2017-08-15          7     DAIRY  1279.0           25
1054885  3000829  2017-08-15          8  CLEANING  1198.0           13
1054886  3000830  2017-08-15          8     DAIRY  1330.0           24
1054918  3000862  2017-08-15          9  CLEANING  1439.0           25
1054919  3000863  2017-08-15          9     DAIRY   835.0           19

[51864 rows x 6 columns]

In [31]:
oil = pd.read_csv("../retailFiles/oil.csv")
oil["benchmark"] = 100
oil.head()

         date  dcoilwtico  benchmark
0  2013-01-01         NaN        100
1  2013-01-02       93.14        100
2  2013-01-03       92.97        100
3  2013-01-04       93.12        100
4  2013-01-07       93.20        100

In [32]:
oil.dtypes

date           object
dcoilwtico    float64
benchmark       int64
dtype: object

In [37]:
oil["date"] = oil["date"].astype("datetime64[ns]")
oil.dtypes

date          datetime64[ns]
dcoilwtico           float64
benchmark              int64
dtype: object

In [38]:
oil.query("dcoilwtico > benchmark or date.dt. year == 2013")

          date  dcoilwtico  benchmark
0   2013-01-01         NaN        100
1   2013-01-02       93.14        100
2   2013-01-03       92.97        100
3   2013-01-04       93.12        100
4   2013-01-07       93.20        100
..         ...         ...        ...
407 2014-07-24      102.76        100
408 2014-07-25      105.23        100
409 2014-07-28      105.68        100
410 2014-07-29      104.91        100
411 2014-07-30      104.29        100

[367 rows x 3 columns]