In [1]:
import numpy as np
import pandas as pd

sort a DataFrame by its indices using the .sort_index() method (sorts rows axis=0 by default, can specify axis=1 to sort the columns)

sort a DataFrame by its values using the .sort_values() nethod
can sort by a single column or by multiple columns

In [11]:
oil = pd.read_csv("../retailFiles/oil.csv")
oil["benchmark"] = 100
oil

            date  dcoilwtico  benchmark
0     2013-01-01         NaN        100
1     2013-01-02       93.14        100
2     2013-01-03       92.97        100
3     2013-01-04       93.12        100
4     2013-01-07       93.20        100
...          ...         ...        ...
1213  2017-08-25       47.65        100
1214  2017-08-28       46.40        100
1215  2017-08-29       46.46        100
1216  2017-08-30       45.96        100
1217  2017-08-31       47.26        100

[1218 rows x 3 columns]

In [9]:
oil.sort_index(ascending=False)

            date  dcoilwtico  benchmark
1217  2017-08-31       47.26        100
1216  2017-08-30       45.96        100
1215  2017-08-29       46.46        100
1214  2017-08-28       46.40        100
1213  2017-08-25       47.65        100
...          ...         ...        ...
4     2013-01-07       93.20        100
3     2013-01-04       93.12        100
2     2013-01-03       92.97        100
1     2013-01-02       93.14        100
0     2013-01-01         NaN        100

[1218 rows x 3 columns]

In [10]:
oil.sort_index(ascending=False, axis=1)

      dcoilwtico        date  benchmark
0            NaN  2013-01-01        100
1          93.14  2013-01-02        100
2          92.97  2013-01-03        100
3          93.12  2013-01-04        100
4          93.20  2013-01-07        100
...          ...         ...        ...
1213       47.65  2017-08-25        100
1214       46.40  2017-08-28        100
1215       46.46  2017-08-29        100
1216       45.96  2017-08-30        100
1217       47.26  2017-08-31        100

[1218 rows x 3 columns]

In [15]:
oil["month"] = oil["date"].astype("datetime64[ns]").dt.month
oil

            date  dcoilwtico  benchmark  month
0     2013-01-01         NaN        100      1
1     2013-01-02       93.14        100      1
2     2013-01-03       92.97        100      1
3     2013-01-04       93.12        100      1
4     2013-01-07       93.20        100      1
...          ...         ...        ...    ...
1213  2017-08-25       47.65        100      8
1214  2017-08-28       46.40        100      8
1215  2017-08-29       46.46        100      8
1216  2017-08-30       45.96        100      8
1217  2017-08-31       47.26        100      8

[1218 rows x 4 columns]

In [16]:
oil.sort_values("dcoilwtico")

            date  dcoilwtico  benchmark  month
812   2016-02-11       26.19        100      2
796   2016-01-20       26.68        100      1
811   2016-02-10       27.54        100      2
810   2016-02-09       27.96        100      2
795   2016-01-19       28.47        100      1
...          ...         ...        ...    ...
1079  2017-02-20         NaN        100      2
1118  2017-04-14         NaN        100      4
1149  2017-05-29         NaN        100      5
1174  2017-07-03         NaN        100      7
1175  2017-07-04         NaN        100      7

[1218 rows x 4 columns]

In [17]:
oil.sort_values("dcoilwtico", ascending=False)

            date  dcoilwtico  benchmark  month
178   2013-09-06      110.62        100      9
171   2013-08-28      110.17        100      8
179   2013-09-09      109.62        100      9
170   2013-08-27      109.11        100      8
182   2013-09-12      108.72        100      9
...          ...         ...        ...    ...
1079  2017-02-20         NaN        100      2
1118  2017-04-14         NaN        100      4
1149  2017-05-29         NaN        100      5
1174  2017-07-03         NaN        100      7
1175  2017-07-04         NaN        100      7

[1218 rows x 4 columns]

In [18]:
oil.sort_values(["month", "dcoilwtico"], ascending=[True, False])

            date  dcoilwtico  benchmark  month
282   2014-01-30       98.25        100      1
21    2013-01-30       97.98        100      1
22    2013-01-31       97.65        100      1
20    2013-01-29       97.62        100      1
283   2014-01-31       97.55        100      1
...          ...         ...        ...    ...
774   2015-12-21       34.55        100     12
256   2013-12-25         NaN        100     12
517   2014-12-25         NaN        100     12
778   2015-12-25         NaN        100     12
1039  2016-12-26         NaN        100     12

[1218 rows x 4 columns]