In [1]:
import numpy as np
import pandas as pd

In [2]:
oil = pd.read_csv("../retailFiles/oil.csv")
oil["benchmark"] = 90
oil.head()

         date  dcoilwtico  benchmark
0  2013-01-01         NaN         90
1  2013-01-02       93.14         90
2  2013-01-03       92.97         90
3  2013-01-04       93.12         90
4  2013-01-07       93.20         90

In [4]:
oil["benchmark_ratio"] = (oil.loc[:, "dcoilwtico"] / oil.loc[:, "benchmark"]) * 100
oil

            date  dcoilwtico  benchmark  benchmark_ratio
0     2013-01-01         NaN         90              NaN
1     2013-01-02       93.14         90       103.488889
2     2013-01-03       92.97         90       103.300000
3     2013-01-04       93.12         90       103.466667
4     2013-01-07       93.20         90       103.555556
...          ...         ...        ...              ...
1213  2017-08-25       47.65         90        52.944444
1214  2017-08-28       46.40         90        51.555556
1215  2017-08-29       46.46         90        51.622222
1216  2017-08-30       45.96         90        51.066667
1217  2017-08-31       47.26         90        52.511111

[1218 rows x 4 columns]

In [7]:
oil["buy"] = oil.loc[:, "benchmark_ratio"] < 80
oil

            date  dcoilwtico  benchmark  benchmark_ratio    buy
0     2013-01-01         NaN         90              NaN  False
1     2013-01-02       93.14         90       103.488889  False
2     2013-01-03       92.97         90       103.300000  False
3     2013-01-04       93.12         90       103.466667  False
4     2013-01-07       93.20         90       103.555556  False
...          ...         ...        ...              ...    ...
1213  2017-08-25       47.65         90        52.944444   True
1214  2017-08-28       46.40         90        51.555556   True
1215  2017-08-29       46.46         90        51.622222   True
1216  2017-08-30       45.96         90        51.066667   True
1217  2017-08-31       47.26         90        52.511111   True

[1218 rows x 5 columns]

In [8]:
oil["buy"] = (oil.loc[:, "benchmark_ratio"] < 80) * (1000000 / oil.loc[:, "dcoilwtico"])
oil

            date  dcoilwtico  benchmark  benchmark_ratio           buy
0     2013-01-01         NaN         90              NaN           NaN
1     2013-01-02       93.14         90       103.488889      0.000000
2     2013-01-03       92.97         90       103.300000      0.000000
3     2013-01-04       93.12         90       103.466667      0.000000
4     2013-01-07       93.20         90       103.555556      0.000000
...          ...         ...        ...              ...           ...
1213  2017-08-25       47.65         90        52.944444  20986.358867
1214  2017-08-28       46.40         90        51.555556  21551.724138
1215  2017-08-29       46.46         90        51.622222  21523.891520
1216  2017-08-30       45.96         90        51.066667  21758.050479
1217  2017-08-31       47.26         90        52.511111  21159.542954

[1218 rows x 5 columns]