In [1]:
import numpy as np
import pandas as pd

In [3]:
oil = pd.read_csv("../retailFiles/oil.csv")
oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [ ]:
oil.head(5) #return first n rows

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [ ]:
oil.tail(5) #returns last n rows

            date  dcoilwtico
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

In [ ]:
oil.sample(3) #Returns n rows from a random sample

            date  dcoilwtico
1178  2017-07-07       44.25
1120  2017-04-18       52.46
840   2016-03-22       41.45

In [ ]:
oil.info() #Returns key details on DataFrame size, columns, and memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   object
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), object(1)
memory usage: 19.2+ KB

In [ ]:
oil.describe() #return descriptive statistics for the columns in a DataFrame (only numeric columns by default, use the 'include' argument to specify more columns)

        dcoilwtico
count  1175.000000
mean     67.714366
std      25.630476
min      26.190000
25%      46.405000
50%      53.190000
75%      95.660000
max     110.620000