In [1]:
import numpy as np
import pandas as pd

In [3]:
oil = pd.read_csv("../retailFiles/oil.csv")
oil.head(10)

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20
5  2013-01-08       93.21
6  2013-01-09       93.08
7  2013-01-10       93.81
8  2013-01-11       93.60
9  2013-01-14       94.27

In [4]:
oil.tail(7)

            date  dcoilwtico
1211  2017-08-23       48.45
1212  2017-08-24       47.24
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

In [5]:
oil.sample(5)

            date  dcoilwtico
735   2015-10-27       43.21
475   2014-10-28       81.36
318   2014-03-21       99.97
1016  2016-11-23       46.72
628   2015-05-29       60.25

In [6]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   object
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), object(1)
memory usage: 19.2+ KB

In [7]:
oil.describe()

        dcoilwtico
count  1175.000000
mean     67.714366
std      25.630476
min      26.190000
25%      46.405000
50%      53.190000
75%      95.660000
max     110.620000

In [8]:
oil.describe(include='all')

              date   dcoilwtico
count         1218  1175.000000
unique        1218          NaN
top     2013-01-01          NaN
freq             1          NaN
mean           NaN    67.714366
std            NaN    25.630476
min            NaN    26.190000
25%            NaN    46.405000
50%            NaN    53.190000
75%            NaN    95.660000
max            NaN   110.620000

In [9]:
oil.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   object
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), object(1)
memory usage: 19.2+ KB

In [10]:
oil.describe(include='all').round()

              date  dcoilwtico
count         1218      1175.0
unique        1218         NaN
top     2013-01-01         NaN
freq             1         NaN
mean           NaN        68.0
std            NaN        26.0
min            NaN        26.0
25%            NaN        46.0
50%            NaN        53.0
75%            NaN        96.0
max            NaN       111.0