In [1]:
import numpy as np
import pandas as pd

In [5]:
oil = pd.read_csv("../retailFiles/oil.csv")
oil.columns = ["date", "oil price"]
oil.head()

         date  oil price
0  2013-01-01        NaN
1  2013-01-02      93.14
2  2013-01-03      92.97
3  2013-01-04      93.12
4  2013-01-07      93.20

In [6]:
oil.date

0       2013-01-01
1       2013-01-02
2       2013-01-03
3       2013-01-04
4       2013-01-07
           ...
1213    2017-08-25
1214    2017-08-28
1215    2017-08-29
1216    2017-08-30
1217    2017-08-31
Name: date, Length: 1218, dtype: object

In [13]:
oil["oil price"]

0         NaN
1       93.14
2       92.97
3       93.12
4       93.20
        ...
1213    47.65
1214    46.40
1215    46.46
1216    45.96
1217    47.26
Name: oil price, Length: 1218, dtype: float64

In [12]:
oil[["oil price"]]

      oil price
0           NaN
1         93.14
2         92.97
3         93.12
4         93.20
...         ...
1213      47.65
1214      46.40
1215      46.46
1216      45.96
1217      47.26

[1218 rows x 1 columns]

In [11]:
oil[["oil price", "date"]]

      oil price        date
0           NaN  2013-01-01
1         93.14  2013-01-02
2         92.97  2013-01-03
3         93.12  2013-01-04
4         93.20  2013-01-07
...         ...         ...
1213      47.65  2017-08-25
1214      46.40  2017-08-28
1215      46.46  2017-08-29
1216      45.96  2017-08-30
1217      47.26  2017-08-31

[1218 rows x 2 columns]