In [3]:
import numpy as np
import pandas as pd

In [4]:
retail = pd.read_csv('../retailFiles/retail.csv')
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [5]:
retail.iloc[:, 1:4]

               date  store_nbr                      family
0        2016-01-01          1                  AUTOMOTIVE
1        2016-01-01          1                   BABY CARE
2        2016-01-01          1                      BEAUTY
3        2016-01-01          1                   BEVERAGES
4        2016-01-01          1                       BOOKS
...             ...        ...                         ...
1054939  2017-08-15          9                     POULTRY
1054940  2017-08-15          9              PREPARED FOODS
1054941  2017-08-15          9                     PRODUCE
1054942  2017-08-15          9  SCHOOL AND OFFICE SUPPLIES
1054943  2017-08-15          9                     SEAFOOD

[1054944 rows x 3 columns]

In [6]:
retail.iloc[:5, 1:4]

         date  store_nbr      family
0  2016-01-01          1  AUTOMOTIVE
1  2016-01-01          1   BABY CARE
2  2016-01-01          1      BEAUTY
3  2016-01-01          1   BEVERAGES
4  2016-01-01          1       BOOKS

In [7]:
retail.loc[:, "date"]

0          2016-01-01
1          2016-01-01
2          2016-01-01
3          2016-01-01
4          2016-01-01
              ...
1054939    2017-08-15
1054940    2017-08-15
1054941    2017-08-15
1054942    2017-08-15
1054943    2017-08-15
Name: date, Length: 1054944, dtype: object

In [8]:
retail.loc[:, ["date"]]

               date
0        2016-01-01
1        2016-01-01
2        2016-01-01
3        2016-01-01
4        2016-01-01
...             ...
1054939  2017-08-15
1054940  2017-08-15
1054941  2017-08-15
1054942  2017-08-15
1054943  2017-08-15

[1054944 rows x 1 columns]

In [9]:
retail.loc[:, ["date", "sales"]]

               date     sales
0        2016-01-01     0.000
1        2016-01-01     0.000
2        2016-01-01     0.000
3        2016-01-01     0.000
4        2016-01-01     0.000
...             ...       ...
1054939  2017-08-15   438.133
1054940  2017-08-15   154.553
1054941  2017-08-15  2419.729
1054942  2017-08-15   121.000
1054943  2017-08-15    16.000

[1054944 rows x 2 columns]

In [10]:
retail.loc[:, "date":"sales"]

               date  store_nbr                      family     sales
0        2016-01-01          1                  AUTOMOTIVE     0.000
1        2016-01-01          1                   BABY CARE     0.000
2        2016-01-01          1                      BEAUTY     0.000
3        2016-01-01          1                   BEVERAGES     0.000
4        2016-01-01          1                       BOOKS     0.000
...             ...        ...                         ...       ...
1054939  2017-08-15          9                     POULTRY   438.133
1054940  2017-08-15          9              PREPARED FOODS   154.553
1054941  2017-08-15          9                     PRODUCE  2419.729
1054942  2017-08-15          9  SCHOOL AND OFFICE SUPPLIES   121.000
1054943  2017-08-15          9                     SEAFOOD    16.000

[1054944 rows x 4 columns]

In [15]:
oil = pd.read_csv("../retailFiles/oil.csv")
oil.columns = ['date', 'price']
oil.head()

         date  price
0  2013-01-01    NaN
1  2013-01-02  93.14
2  2013-01-03  92.97
3  2013-01-04  93.12
4  2013-01-07  93.20

In [17]:
oil['euro_price'] = oil['price'] * 1.1
oil.head()

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520

In [18]:
oil.iloc[:10, :]

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520
5  2013-01-08  93.21     102.531
6  2013-01-09  93.08     102.388
7  2013-01-10  93.81     103.191
8  2013-01-11  93.60     102.960
9  2013-01-14  94.27     103.697

In [19]:
oil.iloc[:10, -1]

0        NaN
1    102.454
2    102.267
3    102.432
4    102.520
5    102.531
6    102.388
7    103.191
8    102.960
9    103.697
Name: euro_price, dtype: float64

In [20]:
oil.iloc[:10, [-1]]

   euro_price
0         NaN
1     102.454
2     102.267
3     102.432
4     102.520
5     102.531
6     102.388
7     103.191
8     102.960
9     103.697

In [23]:
oil.loc[:5, ["date", "euro_price"]]

         date  euro_price
0  2013-01-01         NaN
1  2013-01-02     102.454
2  2013-01-03     102.267
3  2013-01-04     102.432
4  2013-01-07     102.520
5  2013-01-08     102.531