In [1]:
import numpy as np
import pandas as pd

In [2]:
retail = pd.read_csv("../retailFiles/retail.csv")
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [3]:
retail.drop("id", axis=1).head()

         date  store_nbr      family  sales  onpromotion
0  2016-01-01          1  AUTOMOTIVE    0.0            0
1  2016-01-01          1   BABY CARE    0.0            0
2  2016-01-01          1      BEAUTY    0.0            0
3  2016-01-01          1   BEVERAGES    0.0            0
4  2016-01-01          1       BOOKS    0.0            0

In [6]:
retail.drop(["id", "onpromotion"], axis=1).head() #remove id and onpromotion column

         date  store_nbr      family  sales
0  2016-01-01          1  AUTOMOTIVE    0.0
1  2016-01-01          1   BABY CARE    0.0
2  2016-01-01          1      BEAUTY    0.0
3  2016-01-01          1   BEVERAGES    0.0
4  2016-01-01          1       BOOKS    0.0

In [ ]:
retail.drop([0], axis=0).head() #remove the first row

        id        date  store_nbr        family  sales  onpromotion
1  1945945  2016-01-01          1     BABY CARE    0.0            0
2  1945946  2016-01-01          1        BEAUTY    0.0            0
3  1945947  2016-01-01          1     BEVERAGES    0.0            0
4  1945948  2016-01-01          1         BOOKS    0.0            0
5  1945949  2016-01-01          1  BREAD/BAKERY    0.0            0

In [9]:
#axis=0 for rows
#axis=1 for columns