In [2]:
import numpy as np
import pandas as pd

In [3]:
# .duplicated() method identifies duplicate rows of data
# Specify subet=columns(s) to look for duplicates across a subset of columns

In [4]:
# .drop_duplicates() method drops duplicate rows from a DataFrame
# product_df.drop_duplicates(subset="product", keep="last", ignore_index=True)
# subset="product" will look for duplicates in the product column
# keep="last" will keep the final duplicate row, and drop the rest
# ignore_index=True will reset the index so there are no gaps

In [5]:
oil = pd.read_csv("../retailFiles/oil.csv")
oil.columns = ["date", "price"]
oil["euro_price"] = oil["price"] * 1.1
oil.tail()

            date  price  euro_price
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986

In [6]:
oil = pd.concat([oil, oil.iloc[[-1]]], axis=0, ignore_index=True)
oil.tail()

            date  price  euro_price
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986
1218  2017-08-31  47.26      51.986

In [7]:
oil.shape

(1219, 3)

In [8]:
oil.nunique(dropna=False)

date          1218
price          999
euro_price     999
dtype: int64

In [9]:
oil.duplicated(subset="price")

0       False
1       False
2       False
3       False
4       False
        ...
1214     True
1215     True
1216    False
1217    False
1218     True
Length: 1219, dtype: bool

In [10]:
oil.duplicated(subset="price").sum()
# .sum() for checking how many duplicates

np.int64(220)

In [ ]:
oil.drop_duplicates()
# delete line 1218 because 1218 is a dup

            date  price  euro_price
0     2013-01-01    NaN         NaN
1     2013-01-02  93.14     102.454
2     2013-01-03  92.97     102.267
3     2013-01-04  93.12     102.432
4     2013-01-07  93.20     102.520
...          ...    ...         ...
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986

[1218 rows x 3 columns]

In [ ]:
oil.drop_duplicates(keep='last')
# Keep the last line (1218) but delete line 1217

            date  price  euro_price
0     2013-01-01    NaN         NaN
1     2013-01-02  93.14     102.454
2     2013-01-03  92.97     102.267
3     2013-01-04  93.12     102.432
4     2013-01-07  93.20     102.520
...          ...    ...         ...
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1218  2017-08-31  47.26      51.986

[1218 rows x 3 columns]

In [17]:
oil.drop_duplicates(keep='last', ignore_index=True)

            date  price  euro_price
0     2013-01-01    NaN         NaN
1     2013-01-02  93.14     102.454
2     2013-01-03  92.97     102.267
3     2013-01-04  93.12     102.432
4     2013-01-07  93.20     102.520
...          ...    ...         ...
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986

[1218 rows x 3 columns]

In [ ]:
oil.drop_duplicates(subset=['price'], ignore_index=True)
# sort and only keep the first occurrence of 'price' that appear and delete all the duplicates

           date  price  euro_price
0    2013-01-01    NaN         NaN
1    2013-01-02  93.14     102.454
2    2013-01-03  92.97     102.267
3    2013-01-04  93.12     102.432
4    2013-01-07  93.20     102.520
..          ...    ...         ...
994  2017-08-15  47.57      52.327
995  2017-08-18  48.59      53.449
996  2017-08-21  47.39      52.129
997  2017-08-30  45.96      50.556
998  2017-08-31  47.26      51.986

[999 rows x 3 columns]