In [1]:
import numpy as np
import pandas as pd

In [6]:
retail = pd.read_csv("../retailFiles/retail.csv")
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [ ]:
retail.loc[retail["date"] == "2016-10-28"].head()
#Row filter

             id        date  store_nbr      family   sales  onpromotion
536382  2482326  2016-10-28          1  AUTOMOTIVE     8.0            0
536383  2482327  2016-10-28          1   BABY CARE     0.0            0
536384  2482328  2016-10-28          1      BEAUTY     9.0            1
536385  2482329  2016-10-28          1   BEVERAGES  2576.0           38
536386  2482330  2016-10-28          1       BOOKS     0.0            0

In [ ]:
retail.loc[retail["date"] == "2016-10-28", ["date", "sales"]].head()
#Row and Column filter

              date   sales
536382  2016-10-28     8.0
536383  2016-10-28     0.0
536384  2016-10-28     9.0
536385  2016-10-28  2576.0
536386  2016-10-28     0.0

In [15]:
conds = retail["family"].isin(["CLEANING", "DAIRY"]) & (retail["sales"] > 0)
retail.loc[conds]
#Apply multiple filters by joining the logical tests with an "&" operator

              id        date  store_nbr    family   sales  onpromotion
568      1946512  2016-01-01         25  CLEANING   734.0            0
569      1946513  2016-01-01         25     DAIRY  1033.0           11
1789     1947733  2016-01-02          1  CLEANING   526.0            3
1790     1947734  2016-01-02          1     DAIRY   627.0           15
1822     1947766  2016-01-02         10  CLEANING  1216.0            4
...          ...         ...        ...       ...     ...          ...
1054853  3000797  2017-08-15          7     DAIRY  1279.0           25
1054885  3000829  2017-08-15          8  CLEANING  1198.0           13
1054886  3000830  2017-08-15          8     DAIRY  1330.0           24
1054918  3000862  2017-08-15          9  CLEANING  1439.0           25
1054919  3000863  2017-08-15          9     DAIRY   835.0           19

[62415 rows x 6 columns]

In [17]:
oil = pd.read_csv("../retailFiles/oil.csv")
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [19]:
oil["benchmark"] = 100
oil.head()

         date  dcoilwtico  benchmark
0  2013-01-01         NaN        100
1  2013-01-02       93.14        100
2  2013-01-03       92.97        100
3  2013-01-04       93.12        100
4  2013-01-07       93.20        100

In [21]:
oil.loc[oil["dcoilwtico"] > oil["benchmark"]]

           date  dcoilwtico  benchmark
131  2013-07-03      101.92        100
133  2013-07-05      103.09        100
134  2013-07-08      103.03        100
135  2013-07-09      103.46        100
136  2013-07-10      106.41        100
..          ...         ...        ...
407  2014-07-24      102.76        100
408  2014-07-25      105.23        100
409  2014-07-28      105.68        100
410  2014-07-29      104.91        100
411  2014-07-30      104.29        100

[182 rows x 3 columns]

In [22]:
oil.loc[oil["date"].str[:4] == "2013"]

           date  dcoilwtico  benchmark
0    2013-01-01         NaN        100
1    2013-01-02       93.14        100
2    2013-01-03       92.97        100
3    2013-01-04       93.12        100
4    2013-01-07       93.20        100
..          ...         ...        ...
256  2013-12-25         NaN        100
257  2013-12-26       99.18        100
258  2013-12-27       99.94        100
259  2013-12-30       98.90        100
260  2013-12-31       98.17        100

[261 rows x 3 columns]

In [27]:
mask = ((oil["dcoilwtico"] > oil["benchmark"]) & (oil["date"].str[:4] == "2013"))
oil.loc[mask]

           date  dcoilwtico  benchmark
131  2013-07-03      101.92        100
133  2013-07-05      103.09        100
134  2013-07-08      103.03        100
135  2013-07-09      103.46        100
136  2013-07-10      106.41        100
..          ...         ...        ...
204  2013-10-14      102.46        100
205  2013-10-15      101.15        100
206  2013-10-16      102.34        100
207  2013-10-17      100.72        100
208  2013-10-18      100.87        100

[76 rows x 3 columns]