In [1]:
import pandas as pd

Time delta represent the amount or time, or difference, between two datetimes
- A time delta is returned when subtracting two datetime values

Time delta arithmatic to offset dates by a specified period of time
eg. shipping_dates + pd.to_timedelta(1, unit="D") \
*(2021-04-07 -> 2021-04-08)*

In [2]:
retail = pd.read_csv("../retailFiles/retail_2016_2017.csv", parse_dates=["date"])
retail.head()

        id       date  store_nbr      family  sales  onpromotion
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0
3  1945947 2016-01-01          1   BEVERAGES    0.0            0
4  1945948 2016-01-01          1       BOOKS    0.0            0

In [3]:
retail.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  datetime64[ns]
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 100.4 MB

In [4]:
retail = retail.assign(birthday=pd.to_datetime("1950-01-01"))
retail.head()

        id       date  store_nbr      family  sales  onpromotion   birthday
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0 1950-01-01
1  1945945 2016-01-01          1   BABY CARE    0.0            0 1950-01-01
2  1945946 2016-01-01          1      BEAUTY    0.0            0 1950-01-01
3  1945947 2016-01-01          1   BEVERAGES    0.0            0 1950-01-01
4  1945948 2016-01-01          1       BOOKS    0.0            0 1950-01-01

In [5]:
retail = retail.assign(age=retail["date"] - retail["birthday"])

In [7]:
retail.head()

,id,date,store_nbr,family,sales,onpromotion,birthday,age
0,1945944,2016-01-01,1,AUTOMOTIVE,0.0,0,1950-01-01,24106 days
1,1945945,2016-01-01,1,BABY CARE,0.0,0,1950-01-01,24106 days
2,1945946,2016-01-01,1,BEAUTY,0.0,0,1950-01-01,24106 days
3,1945947,2016-01-01,1,BEVERAGES,0.0,0,1950-01-01,24106 days
4,1945948,2016-01-01,1,BOOKS,0.0,0,1950-01-01,24106 days

In [9]:
retail = retail.assign(age=(retail["date"] - retail["birthday"]).dt.days / 365.25)

In [11]:
retail.head()

,id,date,store_nbr,family,sales,onpromotion,birthday,age
0,1945944,2016-01-01,1,AUTOMOTIVE,0.0,0,1950-01-01,65.998631
1,1945945,2016-01-01,1,BABY CARE,0.0,0,1950-01-01,65.998631
2,1945946,2016-01-01,1,BEAUTY,0.0,0,1950-01-01,65.998631
3,1945947,2016-01-01,1,BEVERAGES,0.0,0,1950-01-01,65.998631
4,1945948,2016-01-01,1,BOOKS,0.0,0,1950-01-01,65.998631

In [13]:
retail = retail.assign(retirement_date = retail["date"] +(pd.to_timedelta(365.25, unit="D")) * 20)
retail.head()

,id,date,store_nbr,family,sales,onpromotion,birthday,age,retirement_date
0,1945944,2016-01-01,1,AUTOMOTIVE,0.0,0,1950-01-01,65.998631,2036-01-01
1,1945945,2016-01-01,1,BABY CARE,0.0,0,1950-01-01,65.998631,2036-01-01
2,1945946,2016-01-01,1,BEAUTY,0.0,0,1950-01-01,65.998631,2036-01-01
3,1945947,2016-01-01,1,BEVERAGES,0.0,0,1950-01-01,65.998631,2036-01-01
4,1945948,2016-01-01,1,BOOKS,0.0,0,1950-01-01,65.998631,2036-01-01