In [1]:
import pandas as pd

.shift() shift a Series by a specifies number of rows

In [2]:
retail = pd.read_csv("../retailFiles/retail_2016_2017.csv", parse_dates=["date"])
retail.head()

        id       date  store_nbr      family  sales  onpromotion
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0
3  1945947 2016-01-01          1   BEVERAGES    0.0            0
4  1945948 2016-01-01          1       BOOKS    0.0            0

In [4]:
retail_agg = retail.groupby(["date"]).agg({"sales":"sum"}).round().iloc[1:10]
retail_agg

                sales
date
2016-01-02  1066677.0
2016-01-03  1226736.0
2016-01-04   955957.0
2016-01-05   835320.0
2016-01-06   821686.0
2016-01-07   653504.0
2016-01-08   713608.0
2016-01-09   989209.0
2016-01-10  1094694.0

In [5]:
retail_agg.assign(yesterday_sales = retail_agg["sales"].shift())

                sales  yesterday_sales
date
2016-01-02  1066677.0              NaN
2016-01-03  1226736.0        1066677.0
2016-01-04   955957.0        1226736.0
2016-01-05   835320.0         955957.0
2016-01-06   821686.0         835320.0
2016-01-07   653504.0         821686.0
2016-01-08   713608.0         653504.0
2016-01-09   989209.0         713608.0
2016-01-10  1094694.0         989209.0

In [6]:
retail_agg.assign(ratio_of_yesterday_sales_and_today_sales = retail_agg["sales"] / retail_agg["sales"].shift())

                sales  ratio_of_yesterday_sales_and_today_sales
date
2016-01-02  1066677.0                                       NaN
2016-01-03  1226736.0                                  1.150054
2016-01-04   955957.0                                  0.779269
2016-01-05   835320.0                                  0.873805
2016-01-06   821686.0                                  0.983678
2016-01-07   653504.0                                  0.795321
2016-01-08   713608.0                                  1.091972
2016-01-09   989209.0                                  1.386208
2016-01-10  1094694.0                                  1.106636