In [1]:
import numpy as np
import pandas as pd

Resampling is a special form of time series aggregation that modifies date indices and fills any gaps to creast continuous date values
- Frequencies are used to define the granularity (you can use years, quarters, and months)

In [2]:
retail = pd.read_csv("../retailFiles/retail_2016_2017.csv", parse_dates=["date"])
retail.head()

        id       date  store_nbr      family  sales  onpromotion
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0
3  1945947 2016-01-01          1   BEVERAGES    0.0            0
4  1945948 2016-01-01          1       BOOKS    0.0            0

In [6]:
retail.groupby([retail["date"].dt.year, retail["date"].dt.month]).sum(numeric_only=True).round(2)

                     id  store_nbr        sales  onpromotion
date date
2016 1     109023650109    1519155  23977804.89       119578
     2     104752572111    1421145  21947408.80       183541
     3     114930124749    1519155  23131780.88       181790
     4     114128305830    1470150  25963025.10       215312
     5     120935040633    1519155  24779432.26       370019
     6     119939514750    1470150  22209218.58       285416
     7     126939956517    1519155  23462672.43       264605
     8     129991635081    1519155  22452414.32       271592
     9     128703960990    1470150  22417448.10       296361
     10    135996550965    1519155  24030389.82       370514
     11    134515169910    1470150  24642640.20       438358
     12    137373141510    1470150  29640287.58       517498
2017 1     144954704169    1519155  26328159.94       363428
     2     133549812396    1372140  23250112.37       297254
     3     150762737565    1519155  26704017.69       339291
     4     148805027910    1470150  25895308.49       371042
     5     156767653449    1519155  26911847.25       414646
     6     154616236830    1470150  25682822.12       394582
     7     162772569333    1519155  27011477.57       409128
     8      79856476425     735075  12433322.94       160278

In [8]:
retail.set_index("date").resample("ME").sum(numeric_only=True).round(2)

                      id  store_nbr        sales  onpromotion
date
2016-01-31  109023650109    1519155  23977804.89       119578
2016-02-29  104752572111    1421145  21947408.80       183541
2016-03-31  114930124749    1519155  23131780.88       181790
2016-04-30  114128305830    1470150  25963025.10       215312
2016-05-31  120935040633    1519155  24779432.26       370019
2016-06-30  119939514750    1470150  22209218.58       285416
2016-07-31  126939956517    1519155  23462672.43       264605
2016-08-31  129991635081    1519155  22452414.32       271592
2016-09-30  128703960990    1470150  22417448.10       296361
2016-10-31  135996550965    1519155  24030389.82       370514
2016-11-30  134515169910    1470150  24642640.20       438358
2016-12-31  137373141510    1470150  29640287.58       517498
2017-01-31  144954704169    1519155  26328159.94       363428
2017-02-28  133549812396    1372140  23250112.37       297254
2017-03-31  150762737565    1519155  26704017.69       339291
2017-04-30  148805027910    1470150  25895308.49       371042
2017-05-31  156767653449    1519155  26911847.25       414646
2017-06-30  154616236830    1470150  25682822.12       394582
2017-07-31  162772569333    1519155  27011477.57       409128
2017-08-31   79856476425     735075  12433322.94       160278

In [9]:
retail.set_index("date").resample("YE").sum(numeric_only=True).round(2)

                       id  store_nbr         sales  onpromotion
date
2016-12-31  1477229623155   17886825  2.886545e+08      3514584
2017-12-31  1132085218077   11124135  1.942171e+08      2749649

In [10]:
retail.set_index("date").resample("QE").sum(numeric_only=True).round(2)

                      id  store_nbr        sales  onpromotion
date
2016-03-31  328706346969    4459455  69056994.57       484909
2016-06-30  355002861213    4459455  72951675.94       870747
2016-09-30  385635552588    4508460  68332534.85       832558
2016-12-31  407884862385    4459455  78313317.59      1326370
2017-03-31  429267254130    4410450  76282290.00       999973
2017-06-30  460188918189    4459455  78489977.87      1180270
2017-09-30  242629045758    2254230  39444800.51       569406