In [1]:
import numpy as np
import pandas as pd

In [2]:
premier_league = pd.read_excel("../retailFiles/premier_league_games_full.xlsx")
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [7]:
premier_league.groupby(["HomeTeam", "season"])[["HomeGoals"]].sum()

                                   HomeGoals
HomeTeam                season
Arsenal                 2008/2009         31
                        2009/2010         48
                        2010/2011         33
                        2011/2012         39
                        2012/2013         47
...                                      ...
Wigan Athletic          2011/2012         22
                        2012/2013         26
Wolverhampton Wanderers 2009/2010         13
                        2010/2011         30
                        2011/2012         19

[160 rows x 1 columns]

In [8]:
premier_league.groupby(["season", "HomeTeam"])[["HomeGoals"]].sum()

                                HomeGoals
season    HomeTeam
2008/2009 Arsenal                      31
          Aston Villa                  27
          Blackburn Rovers             22
          Bolton Wanderers             21
          Chelsea                      33
...                                   ...
2015/2016 Swansea City                 20
          Tottenham Hotspur            35
          Watford                      20
          West Bromwich Albion         20
          West Ham United              34

[160 rows x 1 columns]

In [6]:
premier_league.groupby(["HomeTeam", "season"], as_index=False)[["HomeGoals"]].sum()

                    HomeTeam     season  HomeGoals
0                    Arsenal  2008/2009         31
1                    Arsenal  2009/2010         48
2                    Arsenal  2010/2011         33
3                    Arsenal  2011/2012         39
4                    Arsenal  2012/2013         47
..                       ...        ...        ...
155           Wigan Athletic  2011/2012         22
156           Wigan Athletic  2012/2013         26
157  Wolverhampton Wanderers  2009/2010         13
158  Wolverhampton Wanderers  2010/2011         30
159  Wolverhampton Wanderers  2011/2012         19

[160 rows x 3 columns]

In [11]:
premier_league.groupby(["season", "HomeTeam"], as_index=False)[["HomeGoals"]].sum().query("HomeTeam == 'Arsenal'")

        season HomeTeam  HomeGoals
0    2008/2009  Arsenal         31
20   2009/2010  Arsenal         48
40   2010/2011  Arsenal         33
60   2011/2012  Arsenal         39
80   2012/2013  Arsenal         47
100  2013/2014  Arsenal         36
120  2014/2015  Arsenal         41
140  2015/2016  Arsenal         31