In [1]:
import numpy as np
import pandas as pd

In [4]:
premier_league = pd.read_excel("../retailFiles/premier_league_games_full.xlsx")
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [6]:
agg_prem_league = premier_league.groupby(["season", "HomeTeam"])[["HomeGoals"]].sum()

In [7]:
agg_prem_league.head()

                            HomeGoals
season    HomeTeam
2008/2009 Arsenal                  31
          Aston Villa              27
          Blackburn Rovers         22
          Bolton Wanderers         21
          Chelsea                  33

In [ ]:
agg_prem_league.loc["2008/2009"]

                      HomeGoals
HomeTeam
Arsenal                      31
Aston Villa                  27
Blackburn Rovers             22
Bolton Wanderers             21
Chelsea                      33
Everton                      31
Fulham                       28
Hull City                    18
Liverpool                    41
Manchester City              40
Manchester United            43
Middlesbrough                17
Newcastle United             24
Portsmouth                   26
Stoke City                   22
Sunderland                   21
Tottenham Hotspur            21
West Bromwich Albion         26
West Ham United              23
Wigan Athletic               17

In [9]:
agg_prem_league.loc["2008/2009": "2010/2011"]

                                   HomeGoals
season    HomeTeam
2008/2009 Arsenal                         31
          Aston Villa                     27
          Blackburn Rovers                22
          Bolton Wanderers                21
          Chelsea                         33
          Everton                         31
          Fulham                          28
          Hull City                       18
          Liverpool                       41
          Manchester City                 40
          Manchester United               43
          Middlesbrough                   17
          Newcastle United                24
          Portsmouth                      26
          Stoke City                      22
          Sunderland                      21
          Tottenham Hotspur               21
          West Bromwich Albion            26
          West Ham United                 23
          Wigan Athletic                  17
2009/2010 Arsenal                         48
          Aston Villa                     29
          Birmingham City                 19
          Blackburn Rovers                28
          Bolton Wanderers                26
          Burnley                         25
          Chelsea                         68
          Everton                         35
          Fulham                          27
          Hull City                       22
          Liverpool                       43
          Manchester City                 41
          Manchester United               52
          Portsmouth                      24
          Stoke City                      24
          Sunderland                      32
          Tottenham Hotspur               40
          West Ham United                 30
          Wigan Athletic                  19
          Wolverhampton Wanderers         13
2010/2011 Arsenal                         33
          Aston Villa                     26
          Birmingham City                 19
          Blackburn Rovers                22
          Blackpool                       30
          Bolton Wanderers                34
          Chelsea                         39
          Everton                         31
          Fulham                          30
          Liverpool                       37
          Manchester City                 34
          Manchester United               49
          Newcastle United                41
          Stoke City                      31
          Sunderland                      25
          Tottenham Hotspur               30
          West Bromwich Albion            30
          West Ham United                 24
          Wigan Athletic                  22
          Wolverhampton Wanderers         30

In [10]:
agg_prem_league.loc[("2008/2009", "Arsenal")]

HomeGoals    31
Name: (2008/2009, Arsenal), dtype: int64

In [11]:
agg_prem_league.loc[("2008/2009", "Arsenal"):("2008/2009", "Bolton Wanderers")]

                            HomeGoals
season    HomeTeam
2008/2009 Arsenal                  31
          Aston Villa              27
          Blackburn Rovers         22
          Bolton Wanderers         21

In [12]:
agg_prem_league.iloc[1]

HomeGoals    27
Name: (2008/2009, Aston Villa), dtype: int64

In [14]:
agg_prem_league = premier_league.groupby(["season", "HomeTeam"]).agg({"HomeGoals": ['sum', 'mean']})
agg_prem_league

                               HomeGoals
                                     sum      mean
season    HomeTeam
2008/2009 Arsenal                     31  1.631579
          Aston Villa                 27  1.421053
          Blackburn Rovers            22  1.157895
          Bolton Wanderers            21  1.105263
          Chelsea                     33  1.736842
...                                  ...       ...
2015/2016 Swansea City                20  1.052632
          Tottenham Hotspur           35  1.842105
          Watford                     20  1.052632
          West Bromwich Albion        20  1.052632
          West Ham United             34  1.789474

[160 rows x 2 columns]

In [16]:
agg_prem_league.loc[("2008/2009", "Arsenal"), ("HomeGoals", "mean")]

np.float64(1.631578947368421)