In [11]:
import numpy as np
import pandas as pd

Several ways to modify multi-index DataFrames:
- Reset the index: Move the index levels back to DataFrame columns (sales_sums.reset_index())
- Swap the index level: Changes the hierarchy for the index levels (sales_sums.swaplevel())
- Drop an index level: Drops an index level from the DataFrame entirely (sales)sums.droplevel('family') (!!! May lose important information)

In [12]:
premier_league = pd.read_excel("../retailFiles/premier_league_games_full.xlsx")

In [13]:
agg_prem_league = premier_league.groupby(["season", "HomeTeam"]).agg({"HomeGoals": ['sum', 'mean']})
agg_prem_league.head()

                           HomeGoals
                                 sum      mean
season    HomeTeam
2008/2009 Arsenal                 31  1.631579
          Aston Villa             27  1.421053
          Blackburn Rovers        22  1.157895
          Bolton Wanderers        21  1.105263
          Chelsea                 33  1.736842

In [14]:
agg_prem_league.droplevel(0, axis=1)

                                sum      mean
season    HomeTeam
2008/2009 Arsenal                31  1.631579
          Aston Villa            27  1.421053
          Blackburn Rovers       22  1.157895
          Bolton Wanderers       21  1.105263
          Chelsea                33  1.736842
...                             ...       ...
2015/2016 Swansea City           20  1.052632
          Tottenham Hotspur      35  1.842105
          Watford                20  1.052632
          West Bromwich Albion   20  1.052632
          West Ham United        34  1.789474

[160 rows x 2 columns]

In [15]:
agg_prem_league = agg_prem_league.droplevel(0, axis=1)
agg_prem_league

                                sum      mean
season    HomeTeam
2008/2009 Arsenal                31  1.631579
          Aston Villa            27  1.421053
          Blackburn Rovers       22  1.157895
          Bolton Wanderers       21  1.105263
          Chelsea                33  1.736842
...                             ...       ...
2015/2016 Swansea City           20  1.052632
          Tottenham Hotspur      35  1.842105
          Watford                20  1.052632
          West Bromwich Albion   20  1.052632
          West Ham United        34  1.789474

[160 rows x 2 columns]

In [16]:
agg_prem_league.swaplevel()

                                sum      mean
HomeTeam             season
Arsenal              2008/2009   31  1.631579
Aston Villa          2008/2009   27  1.421053
Blackburn Rovers     2008/2009   22  1.157895
Bolton Wanderers     2008/2009   21  1.105263
Chelsea              2008/2009   33  1.736842
...                             ...       ...
Swansea City         2015/2016   20  1.052632
Tottenham Hotspur    2015/2016   35  1.842105
Watford              2015/2016   20  1.052632
West Bromwich Albion 2015/2016   20  1.052632
West Ham United      2015/2016   34  1.789474

[160 rows x 2 columns]

In [17]:
agg_prem_league.swaplevel().loc["Arsenal"]

           sum      mean
season
2008/2009   31  1.631579
2009/2010   48  2.526316
2010/2011   33  1.736842
2011/2012   39  2.052632
2012/2013   47  2.473684
2013/2014   36  1.894737
2014/2015   41  2.157895
2015/2016   31  1.631579

In [18]:
agg_prem_league.reset_index()

        season              HomeTeam  sum      mean
0    2008/2009               Arsenal   31  1.631579
1    2008/2009           Aston Villa   27  1.421053
2    2008/2009      Blackburn Rovers   22  1.157895
3    2008/2009      Bolton Wanderers   21  1.105263
4    2008/2009               Chelsea   33  1.736842
..         ...                   ...  ...       ...
155  2015/2016          Swansea City   20  1.052632
156  2015/2016     Tottenham Hotspur   35  1.842105
157  2015/2016               Watford   20  1.052632
158  2015/2016  West Bromwich Albion   20  1.052632
159  2015/2016       West Ham United   34  1.789474

[160 rows x 4 columns]