In [12]:
import numpy as np
import pandas as pd

In [13]:
premier_league = pd.read_excel("../retailFiles/premier_league_games_full.xlsx")
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [14]:
premier_league = premier_league.drop(columns=["league_name", "AwayTeam"])

In [ ]:
(
    premier_league
    .groupby(["season", "HomeTeam"], as_index=False)
    .agg(["sum", "mean"])
)

        season              HomeTeam     id              HomeGoals            \
                                        sum         mean       sum      mean
0    2008/2009               Arsenal  36128  1901.473684        31  1.631579
1    2008/2009           Aston Villa  36136  1901.894737        27  1.421053
2    2008/2009      Blackburn Rovers  36781  1935.842105        22  1.157895
3    2008/2009      Bolton Wanderers  36214  1906.000000        21  1.105263
4    2008/2009               Chelsea  36552  1923.789474        33  1.736842
..         ...                   ...    ...          ...       ...       ...
155  2015/2016          Swansea City  87241  4591.631579        20  1.052632
156  2015/2016     Tottenham Hotspur  87218  4590.421053        35  1.842105
157  2015/2016               Watford  87142  4586.421053        20  1.052632
158  2015/2016  West Bromwich Albion  87064  4582.315789        20  1.052632
159  2015/2016       West Ham United  86965  4577.105263        34  1.789474

    AwayGoals
          sum      mean
0          16  0.842105
1          21  1.105263
2          23  1.210526
3          21  1.105263
4          12  0.631579
..        ...       ...
155        20  1.052632
156        15  0.789474
157        19  1.000000
158        26  1.368421
159        26  1.368421

[160 rows x 8 columns]

In [16]:
(
    premier_league
    .groupby(["season", "HomeTeam"], as_index=False)
    .agg({"HomeGoals": ["sum", "mean"],
          "AwayGoals": ["sum", "mean"]
        })
)

        season              HomeTeam HomeGoals           AwayGoals
                                           sum      mean       sum      mean
0    2008/2009               Arsenal        31  1.631579        16  0.842105
1    2008/2009           Aston Villa        27  1.421053        21  1.105263
2    2008/2009      Blackburn Rovers        22  1.157895        23  1.210526
3    2008/2009      Bolton Wanderers        21  1.105263        21  1.105263
4    2008/2009               Chelsea        33  1.736842        12  0.631579
..         ...                   ...       ...       ...       ...       ...
155  2015/2016          Swansea City        20  1.052632        20  1.052632
156  2015/2016     Tottenham Hotspur        35  1.842105        15  0.789474
157  2015/2016               Watford        20  1.052632        19  1.000000
158  2015/2016  West Bromwich Albion        20  1.052632        26  1.368421
159  2015/2016       West Ham United        34  1.789474        26  1.368421

[160 rows x 6 columns]

In [18]:
(
    premier_league
    .groupby(["season", "HomeTeam"], as_index=False)
    .agg(home_goal_sum = ("HomeGoals", "sum"),
         away_goal_sum = ("AwayGoals", "sum")
        )
)

        season              HomeTeam  home_goal_sum  away_goal_sum
0    2008/2009               Arsenal             31             16
1    2008/2009           Aston Villa             27             21
2    2008/2009      Blackburn Rovers             22             23
3    2008/2009      Bolton Wanderers             21             21
4    2008/2009               Chelsea             33             12
..         ...                   ...            ...            ...
155  2015/2016          Swansea City             20             20
156  2015/2016     Tottenham Hotspur             35             15
157  2015/2016               Watford             20             19
158  2015/2016  West Bromwich Albion             20             26
159  2015/2016       West Ham United             34             26

[160 rows x 4 columns]