In [1]:
import numpy as np
import pandas as pd

.transform() method can be used to perform aggregations without reshaping

This is useful for calculating group-level statistics to perform row-level analysis

In [2]:
premier_league = pd.read_excel("../retailFiles/premier_league_games_full.xlsx")
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [11]:
pm = premier_league.assign(
     avg_team_goals = premier_league.groupby(["HomeTeam"])["HomeGoals"].transform("mean"),
     difference = lambda x: x["HomeGoals"] - x["avg_team_goals"]
)
pm

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals,avg_team_goals,difference
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1,2.223684,-1.223684
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0,2.013158,-1.013158
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1,1.210526,-1.210526
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1,1.466165,0.533835
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2,1.177632,2.822368
...,...,...,...,...,...,...,...,...,...
3035,4764,England Premier League,2015/2016,Southampton,Leicester City,2,2,1.763158,0.236842
3036,4765,England Premier League,2015/2016,Swansea City,Stoke City,0,1,1.421053,-1.421053
3037,4766,England Premier League,2015/2016,Tottenham Hotspur,Liverpool,0,0,1.677632,-1.677632
3038,4767,England Premier League,2015/2016,Watford,Arsenal,0,3,1.052632,-1.052632
3039,4768,England Premier League,2015/2016,West Bromwich Albion,Sunderland,1,0,1.330827,-0.330827

In [10]:
pm.groupby(["HomeTeam", "AwayTeam"]).agg({"difference":"mean"}).sort_values("difference")

                                             difference
HomeTeam                AwayTeam
Chelsea                 Bournemouth           -2.190789
Southampton             Wigan Athletic        -1.763158
                        Cardiff City          -1.763158
Leicester City          Hull City             -1.657895
                        Manchester City       -1.657895
...                                                 ...
Wolverhampton Wanderers Blackpool              2.912281
Fulham                  Queens Park Rangers    2.982456
Everton                 Blackpool              3.302632
Leicester City          Queens Park Rangers    3.342105
Arsenal                 Blackpool              3.986842

[932 rows x 1 columns]

In [12]:
pm.query("HomeTeam == 'Arsenal' and AwayTeam == 'Blackpool'")

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals,avg_team_goals,difference
870,2599,England Premier League,2010/2011,Arsenal,Blackpool,6,0,2.013158,3.986842

In [13]:
pm.query("HomeTeam == 'Blackpool'")

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals,avg_team_goals,difference
779,2508,England Premier League,2010/2011,Blackpool,West Bromwich Albion,2,1,1.578947,0.421053
789,2518,England Premier League,2010/2011,Blackpool,Everton,2,2,1.578947,0.421053
819,2548,England Premier League,2010/2011,Blackpool,Wolverhampton Wanderers,2,1,1.578947,0.421053
837,2566,England Premier League,2010/2011,Blackpool,Manchester United,2,3,1.578947,0.421053
857,2586,England Premier League,2010/2011,Blackpool,Tottenham Hotspur,3,1,1.578947,1.421053
869,2598,England Premier League,2010/2011,Blackpool,Liverpool,2,1,1.578947,0.421053
904,2633,England Premier League,2010/2011,Blackpool,Birmingham City,1,2,1.578947,-0.578947
929,2658,England Premier League,2010/2011,Blackpool,Sunderland,1,2,1.578947,-0.578947
936,2665,England Premier League,2010/2011,Blackpool,West Ham United,1,3,1.578947,-0.578947
959,2688,England Premier League,2010/2011,Blackpool,Aston Villa,1,1,1.578947,-0.578947
979,2708,England Premier League,2010/2011,Blackpool,Chelsea,1,3,1.578947,-0.578947
988,2717,England Premier League,2010/2011,Blackpool,Fulham,2,2,1.578947,0.421053
1018,2747,England Premier League,2010/2011,Blackpool,Arsenal,1,3,1.578947,-0.578947
1020,2749,England Premier League,2010/2011,Blackpool,Wigan Athletic,1,3,1.578947,-0.578947
1038,2767,England Premier League,2010/2011,Blackpool,Newcastle United,1,1,1.578947,-0.578947
1047,2776,England Premier League,2010/2011,Blackpool,Stoke City,0,0,1.578947,-1.578947
1067,2796,England Premier League,2010/2011,Blackpool,Bolton Wanderers,4,3,1.578947,2.421053
1109,2838,England Premier League,2010/2011,Blackpool,Blackburn Rovers,1,2,1.578947,-0.578947
1129,2858,England Premier League,2010/2011,Blackpool,Manchester City,2,3,1.578947,0.421053