In [1]:
import numpy as np
import pandas as pd

.pivot_table() method let's you create Excel-style pivot tables

- index: returns a row index with distinct values from the specified column
- columns: returns a column index with distinct values from the specified column
- values: the column, or columns, to perform the aggregations on
- aggfunc: defines the aggregation function, or functions, to perform on the "values"
- margins: returns row and column totals when True (False by default)

In [2]:
premier_league = pd.read_excel("../retailFiles/premier_league_games_full.xlsx")
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [3]:
premier_league.pivot_table(index="HomeTeam",
                           columns="season",
                           values="HomeGoals",
                           aggfunc="sum"
                           )

season,2008/2009,2009/2010,2010/2011,2011/2012,2012/2013,2013/2014,2014/2015,2015/2016
HomeTeam,,,,,,,,
Arsenal,31.0,48.0,33.0,39.0,47.0,36.0,41.0,31.0
Aston Villa,27.0,29.0,26.0,20.0,23.0,22.0,18.0,14.0
Birmingham City,NaN,19.0,19.0,NaN,NaN,NaN,NaN,NaN
Blackburn Rovers,22.0,28.0,22.0,26.0,NaN,NaN,NaN,NaN
Blackpool,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN
Bolton Wanderers,21.0,26.0,34.0,23.0,NaN,NaN,NaN,NaN
Bournemouth,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0
Burnley,NaN,25.0,NaN,NaN,NaN,NaN,14.0,NaN
Cardiff City,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN
Chelsea,33.0,68.0,39.0,41.0,41.0,43.0,36.0,32.0
Crystal Palace,NaN,NaN,NaN,NaN,NaN,18.0,21.0,19.0
Everton,31.0,35.0,31.0,28.0,33.0,38.0,27.0,35.0
Fulham,28.0,27.0,30.0,36.0,28.0,24.0,NaN,NaN
Hull City,18.0,22.0,NaN,NaN,NaN,20.0,19.0,NaN
Leicester City,NaN,NaN,NaN,NaN,NaN,NaN,28.0,35.0
Liverpool,41.0,43.0,37.0,24.0,33.0,53.0,30.0,33.0
Manchester City,40.0,41.0,34.0,55.0,41.0,63.0,44.0,47.0
Manchester United,43.0,52.0,49.0,52.0,45.0,29.0,41.0,27.0
Middlesbrough,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Newcastle United,24.0,NaN,41.0,29.0,24.0,23.0,26.0,32.0
Norwich City,NaN,NaN,NaN,28.0,25.0,17.0,NaN,26.0
Portsmouth,26.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN
Queens Park Rangers,NaN,NaN,NaN,24.0,13.0,NaN,23.0,NaN
Reading,NaN,NaN,NaN,NaN,23.0,NaN,NaN,NaN
Southampton,NaN,NaN,NaN,NaN,26.0,32.0,37.0,39.0
Stoke City,22.0,24.0,31.0,25.0,21.0,27.0,32.0,22.0
Sunderland,21.0,32.0,25.0,26.0,20.0,21.0,16.0,23.0
Swansea City,NaN,NaN,NaN,27.0,28.0,33.0,27.0,20.0
Tottenham Hotspur,21.0,40.0,30.0,39.0,29.0,30.0,31.0,35.0
Watford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0
West Bromwich Albion,26.0,NaN,30.0,21.0,32.0,24.0,24.0,20.0
West Ham United,23.0,30.0,24.0,NaN,34.0,25.0,25.0,34.0
Wigan Athletic,17.0,19.0,22.0,22.0,26.0,NaN,NaN,NaN
Wolverhampton Wanderers,NaN,13.0,30.0,19.0,NaN,NaN,NaN,NaN

In [4]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(index="HomeTeam",
                           columns="season",
                           values="HomeGoals",
                           aggfunc="sum"
                           )

season,2008/2009,2009/2010,2010/2011,2011/2012,2012/2013,2013/2014,2014/2015,2015/2016
HomeTeam,,,,,,,,
Arsenal,31,48,33,39,47,36,41,31
Chelsea,33,68,39,41,41,43,36,32
Everton,31,35,31,28,33,38,27,35

In [5]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(index="HomeTeam",
                           columns="season",
                           values="HomeGoals",
                           aggfunc="sum",
                           margins=True
                           )

season,2008/2009,2009/2010,2010/2011,2011/2012,2012/2013,2013/2014,2014/2015,2015/2016,All
HomeTeam,,,,,,,,,
Arsenal,31,48,33,39,47,36,41,31,306
Chelsea,33,68,39,41,41,43,36,32,333
Everton,31,35,31,28,33,38,27,35,258
All,95,151,103,108,121,117,104,98,897

In [6]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(index="HomeTeam",
                           columns="season",
                           values="HomeGoals",
                           aggfunc=["sum", "mean"]
                           )

               sum                                                    \
season   2008/2009 2009/2010 2010/2011 2011/2012 2012/2013 2013/2014
HomeTeam
Arsenal         31        48        33        39        47        36
Chelsea         33        68        39        41        41        43
Everton         31        35        31        28        33        38

                                  mean                                \
season   2014/2015 2015/2016 2008/2009 2009/2010 2010/2011 2011/2012
HomeTeam
Arsenal         41        31  1.631579  2.526316  1.736842  2.052632
Chelsea         36        32  1.736842  3.578947  2.052632  2.157895
Everton         27        35  1.631579  1.842105  1.631579  1.473684


season   2012/2013 2013/2014 2014/2015 2015/2016
HomeTeam
Arsenal   2.473684  1.894737  2.157895  1.631579
Chelsea   2.157895  2.263158  1.894737  1.684211
Everton   1.736842  2.000000  1.421053  1.842105

In [8]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(index="HomeTeam",
                           columns="season",
                           aggfunc={"HomeGoals":["sum", "mean"], "AwayGoals": ["sum"]}
                           )

         AwayGoals                                                    \
               sum
season   2008/2009 2009/2010 2010/2011 2011/2012 2012/2013 2013/2014
HomeTeam
Arsenal         16        15        15        17        23        11
Chelsea         12        14        13        24        16        11
Everton         20        21        23        15        17        19

                             HomeGoals            ...                      \
                                  mean            ...
season   2014/2015 2015/2016 2008/2009 2009/2010  ... 2014/2015 2015/2016
HomeTeam                                          ...
Arsenal         14        11  1.631579  2.526316  ...  2.157895  1.631579
Chelsea          9        30  1.736842  3.578947  ...  1.894737  1.684211
Everton         21        30  1.631579  1.842105  ...  1.421053  1.842105

                                                                      \
               sum
season   2008/2009 2009/2010 2010/2011 2011/2012 2012/2013 2013/2014
HomeTeam
Arsenal         31        48        33        39        47        36
Chelsea         33        68        39        41        41        43
Everton         31        35        31        28        33        38



season   2014/2015 2015/2016
HomeTeam
Arsenal         41        31
Chelsea         36        32
Everton         27        35

[3 rows x 24 columns]

HEATMAPS: chain .style.background_gradient() to the DataFrame and add a "cmap" argument (axis=None applies the gradient across to the whole table, axis=1 applies the gradient across columns, axis=0 applies the gradient across rows)

In [10]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(index="HomeTeam",
                           columns="season",
                           values="HomeGoals",
                           aggfunc="sum"
                           ).style.background_gradient(cmap="RdYlGn", axis=None)