In [1]:
import numpy as np
import pandas as pd

In [2]:
premier_league = pd.read_excel("../retailFiles/premier_league_games_full.xlsx")
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

.melt() will unpivot a DataFrame, or convert columns into rows

Use the "id_vars" argument to specify the column to unpivot the DataFrame, "value_vars" to select needed value, "var_name" to name value vars column, "value_name" to name value column

In [5]:
premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(index="HomeTeam",
                           columns="season",
                           values="HomeGoals",
                           aggfunc="sum"
                           )

season,2008/2009,2009/2010,2010/2011,2011/2012,2012/2013,2013/2014,2014/2015,2015/2016
HomeTeam,,,,,,,,
Arsenal,31,48,33,39,47,36,41,31
Chelsea,33,68,39,41,41,43,36,32
Everton,31,35,31,28,33,38,27,35

In [6]:
pm = premier_league.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']").pivot_table(index="HomeTeam",
                           columns="season",
                           values="HomeGoals",
                           aggfunc="sum"
                           )

In [8]:
pm.reset_index().melt()

       season    value
0    HomeTeam  Arsenal
1    HomeTeam  Chelsea
2    HomeTeam  Everton
3   2008/2009       31
4   2008/2009       33
5   2008/2009       31
6   2009/2010       48
7   2009/2010       68
8   2009/2010       35
9   2010/2011       33
10  2010/2011       39
11  2010/2011       31
12  2011/2012       39
13  2011/2012       41
14  2011/2012       28
15  2012/2013       47
16  2012/2013       41
17  2012/2013       33
18  2013/2014       36
19  2013/2014       43
20  2013/2014       38
21  2014/2015       41
22  2014/2015       36
23  2014/2015       27
24  2015/2016       31
25  2015/2016       32
26  2015/2016       35

In [10]:
pm.reset_index().melt(id_vars="HomeTeam")

   HomeTeam     season  value
0   Arsenal  2008/2009     31
1   Chelsea  2008/2009     33
2   Everton  2008/2009     31
3   Arsenal  2009/2010     48
4   Chelsea  2009/2010     68
5   Everton  2009/2010     35
6   Arsenal  2010/2011     33
7   Chelsea  2010/2011     39
8   Everton  2010/2011     31
9   Arsenal  2011/2012     39
10  Chelsea  2011/2012     41
11  Everton  2011/2012     28
12  Arsenal  2012/2013     47
13  Chelsea  2012/2013     41
14  Everton  2012/2013     33
15  Arsenal  2013/2014     36
16  Chelsea  2013/2014     43
17  Everton  2013/2014     38
18  Arsenal  2014/2015     41
19  Chelsea  2014/2015     36
20  Everton  2014/2015     27
21  Arsenal  2015/2016     31
22  Chelsea  2015/2016     32
23  Everton  2015/2016     35

In [11]:
pm.reset_index().melt(id_vars="HomeTeam",
                      value_vars=["2008/2009", "2009/2010", "2010/2011"],
                      value_name="avg_goals"
                      )

  HomeTeam     season  avg_goals
0  Arsenal  2008/2009         31
1  Chelsea  2008/2009         33
2  Everton  2008/2009         31
3  Arsenal  2009/2010         48
4  Chelsea  2009/2010         68
5  Everton  2009/2010         35
6  Arsenal  2010/2011         33
7  Chelsea  2010/2011         39
8  Everton  2010/2011         31