Can append, or concatenate, DataFrames with the concat() function\
The columns for the DataFrames should be identical\
pd.concat([df_1, df_2]) will stack the rows from df_2 at the bottom of df_1

In [2]:
import pandas as pd

In [3]:
retail = pd.read_csv("../retailFiles/retail_2016_2017.csv")
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [4]:
automotive = retail.query("family == 'AUTOMOTIVE'").head()
automotive

          id        date  store_nbr      family  sales  onpromotion
0    1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
33   1945977  2016-01-01         10  AUTOMOTIVE    0.0            0
66   1946010  2016-01-01         11  AUTOMOTIVE    0.0            0
99   1946043  2016-01-01         12  AUTOMOTIVE    0.0            0
132  1946076  2016-01-01         13  AUTOMOTIVE    0.0            0

In [5]:
beauty = retail.query("family == 'BEAUTY'").head()
beauty

          id        date  store_nbr  family  sales  onpromotion
2    1945946  2016-01-01          1  BEAUTY    0.0            0
35   1945979  2016-01-01         10  BEAUTY    0.0            0
68   1946012  2016-01-01         11  BEAUTY    0.0            0
101  1946045  2016-01-01         12  BEAUTY    0.0            0
134  1946078  2016-01-01         13  BEAUTY    0.0            0

In [6]:
pd.concat([automotive, beauty])

          id        date  store_nbr      family  sales  onpromotion
0    1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
33   1945977  2016-01-01         10  AUTOMOTIVE    0.0            0
66   1946010  2016-01-01         11  AUTOMOTIVE    0.0            0
99   1946043  2016-01-01         12  AUTOMOTIVE    0.0            0
132  1946076  2016-01-01         13  AUTOMOTIVE    0.0            0
2    1945946  2016-01-01          1      BEAUTY    0.0            0
35   1945979  2016-01-01         10      BEAUTY    0.0            0
68   1946012  2016-01-01         11      BEAUTY    0.0            0
101  1946045  2016-01-01         12      BEAUTY    0.0            0
134  1946078  2016-01-01         13      BEAUTY    0.0            0

In [7]:
pd.concat([automotive, beauty],
          ignore_index=True)

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945977  2016-01-01         10  AUTOMOTIVE    0.0            0
2  1946010  2016-01-01         11  AUTOMOTIVE    0.0            0
3  1946043  2016-01-01         12  AUTOMOTIVE    0.0            0
4  1946076  2016-01-01         13  AUTOMOTIVE    0.0            0
5  1945946  2016-01-01          1      BEAUTY    0.0            0
6  1945979  2016-01-01         10      BEAUTY    0.0            0
7  1946012  2016-01-01         11      BEAUTY    0.0            0
8  1946045  2016-01-01         12      BEAUTY    0.0            0
9  1946078  2016-01-01         13      BEAUTY    0.0            0