In [2]:
import pandas as pd

can join DataFrames with the merge() method\
The DataFrames must sahre at least one column to match the values between them

In [3]:
# left_df.merge(right_df,
#               how, (type of join)
#               left_on, (column(s) in "Left" DataFrame to join by)
#               right_on (column(s) in "Right" DataFrame to join by)
#              )

### Inner Joins

In [4]:
transactions = pd.read_csv("../retailFiles/transactions.csv", parse_dates=["date"])
oil = pd.read_csv("../retailFiles/oil.csv", parse_dates=["date"])

In [5]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  datetime64[ns]
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB

In [6]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[ns]
 1   dcoilwtico  1175 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 19.2 KB

In [7]:
transactions.merge(oil,
                   how="inner",
                   left_on=["date"],
                   right_on=["date"])

            date  store_nbr  transactions  dcoilwtico
0     2013-01-01         25           770         NaN
1     2013-01-02          1          2111       93.14
2     2013-01-02          2          2358       93.14
3     2013-01-02          3          3487       93.14
4     2013-01-02          4          1922       93.14
...          ...        ...           ...         ...
59646 2017-08-15         50          2804       47.57
59647 2017-08-15         51          1573       47.57
59648 2017-08-15         52          2255       47.57
59649 2017-08-15         53           932       47.57
59650 2017-08-15         54           802       47.57

[59651 rows x 4 columns]

### Left Joins

In [11]:
left_joins_table = transactions.merge(oil,
                                      how="left",
                                      left_on=["date"],
                                      right_on=["date"])
left_joins_table

            date  store_nbr  transactions  dcoilwtico
0     2013-01-01         25           770         NaN
1     2013-01-02          1          2111       93.14
2     2013-01-02          2          2358       93.14
3     2013-01-02          3          3487       93.14
4     2013-01-02          4          1922       93.14
...          ...        ...           ...         ...
83483 2017-08-15         50          2804       47.57
83484 2017-08-15         51          1573       47.57
83485 2017-08-15         52          2255       47.57
83486 2017-08-15         53           932       47.57
83487 2017-08-15         54           802       47.57

[83488 rows x 4 columns]

In [ ]:
left_joins_table.loc[left_joins_table["date"] == '2013-01-06'].head() # oil prices are all NaN because of oil table

          date  store_nbr  transactions  dcoilwtico
185 2013-01-06          1           520         NaN
186 2013-01-06          2          1992         NaN
187 2013-01-06          3          3590         NaN
188 2013-01-06          4          1891         NaN
189 2013-01-06          5          1754         NaN

### Outer Joins

In [18]:
transactions.merge(oil,
                   how="outer",
                   left_on=["date"],
                   right_on=["date"]).tail()
# transactions table only go up to 2017-08-15, but oil table go up to 2017-08-31
# That is why store_nbr and transactions are all NaN at the end

            date  store_nbr  transactions  dcoilwtico
83499 2017-08-25        NaN           NaN       47.65
83500 2017-08-28        NaN           NaN       46.40
83501 2017-08-29        NaN           NaN       46.46
83502 2017-08-30        NaN           NaN       45.96
83503 2017-08-31        NaN           NaN       47.26